### ISSUE TITLE
Swift 3 Xcode 8.2.1 not work

### ISSUE THREAD

**Issue by renatords** [hackiftekhar/IQKeyboardManager#739]
Hi. The version 4.0.7 not works with S3 and Xcode 8.2.1. Is there a solution? Tks

**Comment by mhtranbn** [comment]
me too, please suports thank you.

**Comment by MarcusByrd** [comment]
Oh no! I hope this is fixed soon. This keyboard is literally my only life line when it comes to keyboards!

**Comment by KodiKraig** [comment]
It is working for me but extremely slow at times to bring the keyboard up. Not sure what to do to fix this problem.

**Comment by hackiftekhar** [comment]
@renatords @mhtranbn @MarcusByrd @KodiKraig I'll try to add it's support soon.

**Comment by hackiftekhar** [comment]
I checked with Xcode 8.2.1 and it just work fine without any compilation errors.

**Comment by SketchySwift** [comment]
Works fine for me. By the way, how come when the keyboard disappears, it doesn't animated out nicely, neither is there the <> buttons when the keyboard comes up

**Comment by hackiftekhar** [comment]
It doesn't animate nicely with the simulator, but if you are on the real device, then it works well.
